title: Is Pennsylvania Avenue Closed?
domain: ispennsylvaniaavenueclosed.com
description: Crowd sources whether pedestrians can walk down Pennsylvania Avenue in front of the White House
twitter:
  username: penn_ave_status
  account_id: "3031250433"
https: false
